from car_game.wrappers.clip_reward import ClipReward
from car_game.wrappers.discrete_actions import DiscreteActions
from car_game.wrappers.reacher_weighted_reward import ReacherRewardWrapper
from car_game.wrappers.relative_position import RelativePosition
